version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2019
nuget:
  disable_publish_on_pr: true
build_script:
- cmd: .\psake.cmd ci
test: off
artifacts:
- path: build\results\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  server: https://www.myget.org/F/advance-ict/api/v2/package
  api_key:
    secure: zs1JVjFHRdvB36fGq2rN8MR7QeJnCVkt7VTG4ZHT5OYDNpuh2AlGHqK+rseevn8l
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: umTDz107gZIwsL7sFoQncz5lPz/+v+Hj0u7LlidG58vbFKQUYLr68ur+kfRuO55C
  on:
    branch: master
    appveyor_repo_tag: true
